import Head from "next/head";
import { Layout, Posts, SideBar } from "@/components";
import {  useState } from "react";
import axios from "axios";
import  useFetch  from "@/hooks/useFetch";


export default function Home({posts}) {
const [loading, setLoading] = useState(false)
const [data, setData] = useState([])
const [error, setError] = useState(null)


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className="">
        <Layout>
          <div className="home">
            {
              loading ? (
                <p>Loading...</p>
              ) : (
                <>
                  <Posts posts={posts ?? []} />
                  <SideBar />
                </>
              )
            }
          </div>
        </Layout>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/posts`)
  const data = res.data

  return {
    props: {
      posts: data
    }
  }
}
